name: to_do
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:



  get: ^4.6.6

  flutter:
    sdk: flutter


    # Firebase Core
  firebase_core: ^3.4.0

    # Firestore
  cloud_firestore: ^5.3.0

  firebase_storage: ^12.2.0
  image_picker: ^0.8.7+4

  intl: ^0.18.1

    # Diğer Firebase paketleri (Gerekirse)
  firebase_auth: ^5.2.0

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.1.0

  intl_phone_field: ^3.2.0

dev_dependencies:

  flutter_launcher_icons: ^0.9.2



  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:




  uses-material-design: true


  assets:
      - assets/images/


  fonts:
    - family: Lili
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Protest
      fonts:
        - asset: assets/fonts/ProtestGuerrilla-Regular.ttf


flutter_icons:
    android: true
    image_path: "assets/images/appicon.png"